#!/bin/bash
set -e

WORKSPACE="/comfyui"
EXTRA_PATHS_FILE="${WORKSPACE}/extra_model_paths.yaml"
BAKED_MODELS="${WORKSPACE}/models"
NETWORK_VOLUME_PATH="${NETWORK_VOLUME_PATH:-/runpod-volume}"
NETWORK_MODELS="${NETWORK_VOLUME_PATH}/models"

echo "================================================"
echo "🚀 PSEUDOTOOLS COMFYUI WORKER STARTUP"
echo "================================================"
echo "🔧 Configuring ComfyUI model paths..."
echo "  • Baked-in models:    ${BAKED_MODELS}"
echo "  • Network volume path: ${NETWORK_MODELS}"
echo "================================================"

# Run handler diagnostic
echo "🔍 Running handler diagnostic..."
/app/diagnose_handler.sh

mkdir -p "${BAKED_MODELS}"

# Ensure file exists and starts with a header if empty
if [ ! -s "${EXTRA_PATHS_FILE}" ]; then
    echo "# Generated by Pseudotools setup_models.sh" > "${EXTRA_PATHS_FILE}"
    echo "" >> "${EXTRA_PATHS_FILE}"
fi

# Remove any old custom_models section to avoid duplication
sed -i '/^custom_models:/,$d' "${EXTRA_PATHS_FILE}"

# Start new section for baked-in models
{
  echo ""
  echo "custom_models:"
  echo "  checkpoints: ${BAKED_MODELS}/checkpoints"
  echo "  clip:        ${BAKED_MODELS}/clip"
  echo "  clip_vision: ${BAKED_MODELS}/clip_vision"
  echo "  controlnet:  ${BAKED_MODELS}/controlnet"
  echo "  ipadapter:   ${BAKED_MODELS}/ipadapter"
  echo "  loras:       ${BAKED_MODELS}/loras"
} >> "${EXTRA_PATHS_FILE}"

# If network volume exists, append those directories
if [ -d "${NETWORK_MODELS}" ]; then
  echo "✅ Found network models at ${NETWORK_MODELS}"
  for folder in checkpoints clip clip_vision controlnet ipadapter loras; do
    subdir="${NETWORK_MODELS}/${folder}"
    if [ -d "${subdir}" ]; then
      echo "  + Adding ${subdir} to extra_model_paths.yaml"
      echo "  ${folder}_shared: ${subdir}" >> "${EXTRA_PATHS_FILE}"
    fi
  done
else
  echo "⚠️  No network volume found at ${NETWORK_MODELS} (continuing with baked-in models only)"
fi

echo "────────────────────────────────────────────"
echo "🧩 Final model paths written to ${EXTRA_PATHS_FILE}:"
cat "${EXTRA_PATHS_FILE}"
echo "────────────────────────────────────────────"

# Runtime diagnostics
echo "🧩 Model paths available at runtime:"
find /comfyui/models -maxdepth 2 -type f -name "*.safetensors" || echo "❌ No models found"
if [ -f /comfyui/extra_model_paths.yaml ]; then
  echo "🔧 extra_model_paths.yaml:"
  cat /comfyui/extra_model_paths.yaml
else
  echo "⚠️ No extra_model_paths.yaml found"
fi

echo "================================================"
echo "✅ PSEUDOTOOLS WORKER CONFIGURATION COMPLETE"
echo "🚀 Starting ComfyUI worker..."
echo "================================================"

# Start the worker normally
exec /start.sh
